services:
  backend:
    build: ../backend
    container_name: backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/db-big-data
    ports:
      - "8000:8000"

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-big-data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
